name: "➕ einen neuen Makerspace hinzufügen"
description: "Trage hier die Daten für einen neuen Makerspace ein."
title: "neuer Makerspace"
#labels: ["add-space"]
body:
  - type: markdown
    attributes:
      value: |
        ### Thanks for the new entry. 💛
        Please fill all fields correctly - SpaceAPI is helpful, but optional
  - type: input
    id: name
    attributes:
      label: Name des Makerspaces
      placeholder: "title of your makerspace"
    validations:
      required: true
  - type: dropdown
    id: country
    attributes:
      label: Land
      options:
        - "Germany"
        - "Austria"
        - "Switzerland"
        - "Netherlands"
        - "Belgium"
        - "Denmark"
        - "Ukraine"
        - "other"
    validations:
      required: true
  - type: input
    id: city
    attributes:
      label: Stadt
    validations:
      required: true
  - type: input
    id: plz
    attributes:
      label: PLZ
    validations:
      required: true
  - type: input
    id: street_name
    attributes:
      label: Straße
    validations:
      required: true
  - type: input
    id: street_number
    attributes:
      label: Hausnummer
    validations:
      required: true
  - type: input
    id: street_ext
    attributes:
      label: Adress-Zusatz
      placeholder: "additional address details"
  - type: input
    id: lat
    attributes:
      label: Latitude (Breitengrad)
      placeholder: "47.7126816 - latitude w/ point"
    validations:
      required: true
  - type: input
    id: long
    attributes:
      label: Longitude (Längengrad)
      placeholder: "9.3995537 - longitude w/ point"
    validations:
      required: true
  - type: dropdown
    id: style
    attributes:
      label: Kategorie / Style
      options:
        - "for all"
        - "for youth"
        - "for students"
        - "commercial"
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: Webseite (URL)
      placeholder: "your makerspace homepage url"
    validations:
      required: true
  - type: input
    id: url_text
    attributes:
      label: Link-Anzeigetext
      placeholder: "short form of url - e.g. toolbox-bodensee.de"
    validations:
      required: true
  - type: input
    id: spaceapi
    attributes:
      label: SpaceAPI Endpoint (Optional)
      description: "Falls vorhanden, die URL zur JSON-Datei des Space-Status."
      placeholder: "full url of. SpaceAPI endpoint"
