name: "➕ Add a new Makerspace"
description: "Submit the details for a new makerspace."
title: "new makerspace"
labels:
  - add-space
body:
  - type: markdown
    attributes:
      value: |
        ### Thanks for the new entry. 💛
        Please fill all fields correctly - SpaceAPI is helpful, but optional
  - type: input
    id: name
    attributes:
      label: Name
      placeholder: "title of your makerspace"
    validations:
      required: true
  - type: dropdown
    id: country
    attributes:
      label: Country
      options:
        - "Germany"
        - "Austria"
        - "Switzerland"
        - "Netherlands"
        - "Belgium"
        - "Denmark"
        - "Ukraine"
        - "other"
    validations:
      required: true
  - type: input
    id: city
    attributes:
      label: City
    validations:
      required: true
  - type: input
    id: plz
    attributes:
      label: Postal code
    validations:
      required: true
  - type: input
    id: street_name
    attributes:
      label: Street
    validations:
      required: true
  - type: input
    id: street_number
    attributes:
      label: Street number
    validations:
      required: true
  - type: input
    id: street_ext
    attributes:
      label: Address addition
      placeholder: "additional address details"
  - type: input
    id: lat
    attributes:
      label: Latitude
      placeholder: "47.7126816 - latitude w/ point"
    validations:
      required: true
  - type: input
    id: long
    attributes:
      label: Longitude
      placeholder: "9.3995537 - longitude w/ point"
    validations:
      required: true
  - type: dropdown
    id: style
    attributes:
      label: Style
      options:
        - "for all"
        - "for youth"
        - "for students"
        - "commercial"
    validations:
      required: true
  - type: checkboxes
    id: workshops
    attributes:
      label: Workshop types (optional)
      options:
        - label: "3D printing"
        - label: "Laser cutting"
        - label: "Electronics"
        - label: "Woodworking"
        - label: "Metalworking"
        - label: "Textile"
        - label: "Screen printing"
        - label: "Music"
        - label: "Coding"
        - label: "VR"
  - type: input
    id: url
    attributes:
      label: Website (URL)
      placeholder: "your makerspace homepage url"
    validations:
      required: true
  - type: input
    id: url_text
    attributes:
      label: Link display text
      placeholder: "short form of url - e.g. toolbox-bodensee.de"
    validations:
      required: true
  - type: dropdown
    id: weekly_weekday
    attributes:
      label: Weekly open day (optional)
      description: "Which weekday does your regular open meeting take place?"
      options:
        - "none"
        - "Monday"
        - "Tuesday"
        - "Wednesday"
        - "Thursday"
        - "Friday"
        - "Saturday"
        - "Sunday"
  - type: input
    id: weekly_time
    attributes:
      label: Weekly open time (optional)
      description: "Time in HHMM format, e.g. 1900 for 7:00 PM."
      placeholder: "1900"
  - type: input
    id: spaceapi
    attributes:
      label: SpaceAPI Endpoint (optional)
      description: "If available, the URL to the SpaceAPI JSON endpoint."
      placeholder: "full url of SpaceAPI endpoint"
